# Generated by Django 3.0.6 on 2020-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
