# Generated by Django 3.0.6 on 2020-09-22 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0012_auto_20200920_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='venda_produto',
            name='data',
            field=models.DateField(default=datetime.date(2020, 9, 22)),
        ),
        migrations.AddField(
            model_name='venda_produto',
            name='quantidade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
