# Generated by Django 3.0.6 on 2020-09-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0015_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
