# Generated by Django 3.0.6 on 2020-09-28 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0016_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda_produto',
            name='data',
            field=models.DateField(default=datetime.date(2020, 9, 28)),
        ),
    ]
