# Generated by Django 3.0.6 on 2020-09-28 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projpad', '0020_auto_20200928_0647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='data_criada',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='tel',
            new_name='phone',
        ),
    ]
