# Generated by Django 3.0.6 on 2020-09-28 10:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projpad', '0021_auto_20200928_0728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='date_created',
            new_name='data_criada',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='phone',
            new_name='tel',
        ),
    ]
