# Generated by Django 3.0.6 on 2020-10-09 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0022_auto_20200928_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda_produto',
            name='data',
            field=models.DateField(default=datetime.date(2020, 10, 9)),
        ),
    ]
