# Generated by Django 3.0.6 on 2020-10-12 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0023_auto_20201009_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda_produto',
            name='data',
            field=models.DateField(default=datetime.date(2020, 10, 12)),
        ),
    ]
