# Generated by Django 3.0.6 on 2020-10-14 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0026_auto_20201013_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda_produto',
            name='data',
            field=models.DateField(default=datetime.date(2020, 10, 14)),
        ),
    ]
