# Generated by Django 3.0.6 on 2020-10-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('projpad', '0027_auto_20201014_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda_produto',
            name='fkproduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto'),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='TipoProduto',
        ),
    ]
