# Generated by Django 3.0.6 on 2020-10-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0028_auto_20201014_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda_produto',
            name='fkproduto',
        ),
        migrations.RemoveField(
            model_name='venda_produto',
            name='fkvenda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
        migrations.DeleteModel(
            name='Venda_Produto',
        ),
    ]
