# Generated by Django 3.0.6 on 2020-10-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0029_auto_20201014_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
