# Generated by Django 3.0.6 on 2020-10-22 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0005_auto_20201022_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda_produto',
            name='data',
        ),
        migrations.AddField(
            model_name='venda_produto',
            name='datacriacao',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='venda_produto',
            name='datamodificacao',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='venda_produto',
            name='fkfuncionario',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda_produto',
            name='precovenda',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
