# Generated by Django 3.0.6 on 2020-10-22 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0006_auto_20201022_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda_produto',
            old_name='datacriacao',
            new_name='pdatacriacao',
        ),
        migrations.RenameField(
            model_name='venda_produto',
            old_name='datamodificacao',
            new_name='pdatamodificacao',
        ),
        migrations.RemoveField(
            model_name='venda_produto',
            name='fkfuncionario',
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdatacriacao', models.DateField(editable=False, null=True)),
                ('vdatamodificacao', models.DateField(editable=False, null=True)),
                ('fkfuncionario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='venda_produto',
            name='fkvenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.Venda'),
        ),
    ]
