# Generated by Django 3.0.6 on 2020-10-22 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0007_auto_20201022_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdatacriacao', models.DateField(editable=False, null=True)),
                ('vdatamodificacao', models.DateField(editable=False, null=True)),
                ('fkfuncionario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='venda_produto',
            name='fkvenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.Venda2'),
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
