# Generated by Django 3.0.6 on 2020-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_auto_20201027_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda_produto',
            name='campo_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
