# Generated by Django 3.0.6 on 2020-10-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_venda_produto_campo_calculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda_produto',
            name='campo_calculado',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
