# Generated by Django 3.0.6 on 2020-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_auto_20201028_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda_produto',
            name='campo_calculado',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
