# Generated by Django 3.0.6 on 2020-10-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_auto_20201028_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda_produto',
            name='campo_calculado',
        ),
        migrations.CreateModel(
            name='Venda_Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_calculado', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.Venda_Produto')),
            ],
        ),
    ]
