# Generated by Django 3.0.6 on 2020-10-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0013_auto_20201028_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda_total',
            name='campo_calculado',
        ),
        migrations.RemoveField(
            model_name='venda_total',
            name='preco',
        ),
        migrations.AddField(
            model_name='venda_total',
            name='multtotal',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.Venda_Produto'),
        ),
    ]
