# Generated by Django 3.0.6 on 2020-10-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_auto_20201030_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda_produto',
            name='multtotal',
            field=models.FloatField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Venda_Total',
        ),
    ]
