# Generated by Django 3.0.6 on 2020-10-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0016_auto_20201030_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda_produto',
            name='multtotal',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
