# Generated by Django 3.0.6 on 2020-10-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0018_auto_20201030_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda_produto',
            name='multtotal',
        ),
    ]
